#!/usr/bin/env node
import { build } from 'vite'
import { build as esbuild, transform } from 'esbuild'
import * as fs from 'node:fs'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
import { createUI, collectBuildInfo } from 'gas-app-kit'

const ui = createUI('build')
const __dirname = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(__dirname, '..')
const DIST = path.join(ROOT, 'dist')
const BUILD = path.join(ROOT, 'build')

async function buildClient() {
  await build({ root: ROOT })
  const file = path.join(DIST, 'app.js')
  const { code } = await transform(fs.readFileSync(file, 'utf-8'), {
    supported: { 'template-literal': false },
  })
  fs.writeFileSync(file, code.replaceAll('`', '\\u0060'))
  ui.item('client bundled')
}

function stripGasSyntax(code) {
  return code
    .replace(/export\s*\{[\s\S]*?\}\s*;?\s*/g, '')
    .replace(/^export\s+/gm, '')
    .replace(/^import\s+.*$/gm, '')
    .replace(/\n{3,}/g, '\n\n')
}

function buildBanner(info) {
  return `/**
 * AUTO-GENERATED — DO NOT EDIT
 * Generated by scripts/build.mjs.
 *
 * version : ${info.version}
 * commit  : ${info.commit}${info.dirty ? ' (dirty)' : ''}
 * branch  : ${info.branch}
 * env     : ${info.env}
 * builtAt : ${info.builtAt}
 */
`
}

async function buildServer(info) {
  const result = await esbuild({
    entryPoints: [path.join(ROOT, 'src/server/index.ts')],
    bundle: true,
    format: 'esm',
    target: ['es2019'],
    write: false,
  })
  const code = stripGasSyntax(result.outputFiles[0].text)
  fs.writeFileSync(path.join(BUILD, 'Code.gs'), buildBanner(info) + '\n' + code)
  ui.item('server bundled -> Code.gs')
}

function escapeJsForGas(js) {
  let out = js.replace(/<\/script\s*>/gi, '<\\/script>')
  out = out.replace(/:\/\//g, ':\\u002F\\u002F')
  return out
}

function generateHtml() {
  const cssPath = path.join(DIST, 'app.css')
  const css = fs.existsSync(cssPath) ? fs.readFileSync(cssPath, 'utf-8') : ''
  const safeCss = css.replace(/<\/style\s*>/gi, '\\3C/style>')
  const js = escapeJsForGas(fs.readFileSync(path.join(DIST, 'app.js'), 'utf-8'))

  const indexHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <style>${safeCss}</style>
</head>
<body>
  <div id="app"></div>
  <?!= include('app') ?>
</body>
</html>`

  fs.writeFileSync(path.join(BUILD, 'index.html'), indexHtml)
  fs.writeFileSync(path.join(BUILD, 'app.html'), `<script>${js}</script>`)
  ui.item('index.html + app.html generated')
}

function copyAppsScript() {
  fs.copyFileSync(
    path.join(ROOT, 'appsscript.json'),
    path.join(BUILD, 'appsscript.json'),
  )
  ui.item('appsscript.json copied')
}

async function main() {
  fs.mkdirSync(DIST, { recursive: true })
  fs.mkdirSync(BUILD, { recursive: true })

  ui.banner()
  ui.setTotal(4)

  const info = collectBuildInfo({
    env: process.env.BUILD_ENV ?? 'local',
    cwd: ROOT,
  })

  try {
    ui.step('Client')
    await buildClient()
    ui.step('Server')
    await buildServer(info)
    ui.step('HTML')
    generateHtml()
    ui.step('Manifest')
    copyAppsScript()
    ui.done(`Build complete -> ${BUILD}`)
  } catch (err) {
    ui.fail(`Build failed: ${err.message || err}`)
  }
}

main()
